//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIL.Transcelerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QTTallBooks.sfm")]
        public string QuestionsFile {
            get {
                return ((string)(this["QuestionsFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState DefaultWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["DefaultWindowState"]));
            }
            set {
                this["DefaultWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KeyTermFilterType {
            get {
                return ((int)(this["KeyTermFilterType"]));
            }
            set {
                this["KeyTermFilterType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchPartialWords {
            get {
                return ((bool)(this["MatchPartialWords"]));
            }
            set {
                this["MatchPartialWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolbar {
            get {
                return ((bool)(this["ShowToolbar"]));
            }
            set {
                this["ShowToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendScrRefs {
            get {
                return ((bool)(this["SendScrRefs"]));
            }
            set {
                this["SendScrRefs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReceiveScrRefs {
            get {
                return ((bool)(this["ReceiveScrRefs"]));
            }
            set {
                this["ReceiveScrRefs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAnswersAndComments {
            get {
                return ((bool)(this["ShowAnswersAndComments"]));
            }
            set {
                this["ShowAnswersAndComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76")]
        public int MaximumHeightOfKeyTermsPane {
            get {
                return ((int)(this["MaximumHeightOfKeyTermsPane"]));
            }
            set {
                this["MaximumHeightOfKeyTermsPane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GenerateTemplateRange {
            get {
                return ((int)(this["GenerateTemplateRange"]));
            }
            set {
                this["GenerateTemplateRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateTemplateBook {
            get {
                return ((string)(this["GenerateTemplateBook"]));
            }
            set {
                this["GenerateTemplateBook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateTemplateSection {
            get {
                return ((string)(this["GenerateTemplateSection"]));
            }
            set {
                this["GenerateTemplateSection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateTemplateEndSection {
            get {
                return ((string)(this["GenerateTemplateEndSection"]));
            }
            set {
                this["GenerateTemplateEndSection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateTemplatePassageBeforeOverview {
            get {
                return ((bool)(this["GenerateTemplatePassageBeforeOverview"]));
            }
            set {
                this["GenerateTemplatePassageBeforeOverview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateTemplateEnglishQuestions {
            get {
                return ((bool)(this["GenerateTemplateEnglishQuestions"]));
            }
            set {
                this["GenerateTemplateEnglishQuestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateTemplateEnglishAnswers {
            get {
                return ((bool)(this["GenerateTemplateEnglishAnswers"]));
            }
            set {
                this["GenerateTemplateEnglishAnswers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateTemplateIncludeComments {
            get {
                return ((bool)(this["GenerateTemplateIncludeComments"]));
            }
            set {
                this["GenerateTemplateIncludeComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateTemplateUseOriginalQuestionIfNotTranslated {
            get {
                return ((bool)(this["GenerateTemplateUseOriginalQuestionIfNotTranslated"]));
            }
            set {
                this["GenerateTemplateUseOriginalQuestionIfNotTranslated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GenerateTemplateBlankLines {
            get {
                return ((int)(this["GenerateTemplateBlankLines"]));
            }
            set {
                this["GenerateTemplateBlankLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateTemplateNumberQuestions {
            get {
                return ((bool)(this["GenerateTemplateNumberQuestions"]));
            }
            set {
                this["GenerateTemplateNumberQuestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateTemplateUseExternalCss {
            get {
                return ((bool)(this["GenerateTemplateUseExternalCss"]));
            }
            set {
                this["GenerateTemplateUseExternalCss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string GenerateTemplateCssFile {
            get {
                return ((string)(this["GenerateTemplateCssFile"]));
            }
            set {
                this["GenerateTemplateCssFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateTemplateAbsoluteCssPath {
            get {
                return ((bool)(this["GenerateTemplateAbsoluteCssPath"]));
            }
            set {
                this["GenerateTemplateAbsoluteCssPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color GenerateTemplateQuestionGroupHeadingsColor {
            get {
                return ((global::System.Drawing.Color)(this["GenerateTemplateQuestionGroupHeadingsColor"]));
            }
            set {
                this["GenerateTemplateQuestionGroupHeadingsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GenerateTemplateEnglishQuestionTextColor {
            get {
                return ((global::System.Drawing.Color)(this["GenerateTemplateEnglishQuestionTextColor"]));
            }
            set {
                this["GenerateTemplateEnglishQuestionTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GenerateTemplateEnglishAnswerTextColor {
            get {
                return ((global::System.Drawing.Color)(this["GenerateTemplateEnglishAnswerTextColor"]));
            }
            set {
                this["GenerateTemplateEnglishAnswerTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GenerateTemplateCommentTextColor {
            get {
                return ((global::System.Drawing.Color)(this["GenerateTemplateCommentTextColor"]));
            }
            set {
                this["GenerateTemplateCommentTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GenerateTemplateFolder {
            get {
                return ((string)(this["GenerateTemplateFolder"]));
            }
            set {
                this["GenerateTemplateFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FilterStartRef {
            get {
                return ((int)(this["FilterStartRef"]));
            }
            set {
                this["FilterStartRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FilterEndRef {
            get {
                return ((int)(this["FilterEndRef"]));
            }
            set {
                this["FilterEndRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeNeeded {
            get {
                return ((bool)(this["UpgradeNeeded"]));
            }
            set {
                this["UpgradeNeeded"] = value;
            }
        }
    }
}
